// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scheduling.Domain;

namespace Scheduling.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20210511095901_AddVacationResponses")]
    partial class AddVacationResponses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Scheduling.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Accountant"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Part-time"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Full-time"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Access to reports"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Access to calendar"
                        });
                });

            modelBuilder.Entity("Scheduling.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            CreatorId = 1321313,
                            Name = "Development"
                        });
                });

            modelBuilder.Entity("Scheduling.Models.TimerHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TimerHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FinishTime = new DateTime(2021, 1, 1, 1, 1, 2, 0, DateTimeKind.Unspecified),
                            StartTime = new DateTime(2021, 1, 1, 1, 1, 1, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Scheduling.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Jwt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("Scheduling.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1321313,
                            Department = "Nachalstvo",
                            Email = "admin@gmail.com",
                            Name = "Denis",
                            Password = "5dj3bhWCfxuHmONkBdvFrA==",
                            Position = "Nachalnik",
                            Salt = "91ed90df-3289-4fdf-a927-024b24bea8b7",
                            Surname = "Pensiya"
                        },
                        new
                        {
                            Id = 1321314,
                            Department = "Nachalstvo",
                            Email = "admin2@gmail.com",
                            Name = "Arkadiy",
                            Password = "5dj3bhWCfxuHmONkBdvFrA==",
                            Position = "Pochti nachalstvo",
                            Salt = "91ed90df-3289-4fdf-a927-024b24bea8b7",
                            Surname = "Cisterna"
                        },
                        new
                        {
                            Id = 1321315,
                            Department = "Nachalstvo",
                            Email = "admin3@gmail.com",
                            Name = "Arkadiy",
                            Password = "5dj3bhWCfxuHmONkBdvFrA==",
                            Position = "Pochti nachalstvo",
                            Salt = "91ed90df-3289-4fdf-a927-024b24bea8b7",
                            Surname = "Cisterna"
                        },
                        new
                        {
                            Id = 13213133,
                            Department = "Memes",
                            Email = "user@gmail.com",
                            Name = "User",
                            Password = "u9DAYiHl+liIqRMvuuciBA==",
                            Position = "lol",
                            Salt = "f0e30e73-fac3-4182-8641-ecba862fed69",
                            Surname = "Userov"
                        });
                });

            modelBuilder.Entity("Scheduling.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PermisionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermisionId = 3,
                            UserId = 13213133
                        },
                        new
                        {
                            Id = 2,
                            PermisionId = 1,
                            UserId = 1321313
                        },
                        new
                        {
                            Id = 3,
                            PermisionId = 2,
                            UserId = 1321313
                        },
                        new
                        {
                            Id = 4,
                            PermisionId = 1,
                            UserId = 1321314
                        },
                        new
                        {
                            Id = 5,
                            PermisionId = 2,
                            UserId = 1321314
                        },
                        new
                        {
                            Id = 6,
                            PermisionId = 1,
                            UserId = 1321315
                        },
                        new
                        {
                            Id = 7,
                            PermisionId = 2,
                            UserId = 1321315
                        });
                });

            modelBuilder.Entity("Scheduling.Models.UserTeams", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("userTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TeamId = 6,
                            UserId = 13213133
                        });
                });

            modelBuilder.Entity("Scheduling.Models.UserTimerHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("TimerHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserTimerHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TimerHistoryId = 1,
                            UserId = 1321313
                        });
                });

            modelBuilder.Entity("Scheduling.Models.VacationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("VacationRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "I want to see a bober.",
                            FinishDate = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 13213133
                        },
                        new
                        {
                            Id = 2,
                            Comment = "I really want to see a bober.",
                            FinishDate = new DateTime(2021, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 13213133
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Please, it`s my dream to see a bober.",
                            FinishDate = new DateTime(2021, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2021, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 13213133
                        });
                });

            modelBuilder.Entity("Scheduling.Models.VacationResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("ResponderId")
                        .HasColumnType("int");

                    b.Property<bool>("Response")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("VacationResponses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "No problem. Let`s go!",
                            RequestId = 1,
                            ResponderId = 1321313,
                            Response = true
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Oke. Goodbye :(((((((((",
                            RequestId = 1,
                            ResponderId = 1321314,
                            Response = true
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Nea. Sidi tut!",
                            RequestId = 1,
                            ResponderId = 1321315,
                            Response = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
